apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "/Users/chenw/.kube/config"
profiles:
- schedulerName: scorebylabel
  plugins:
    score:
      enabled:
      - name: ScoreByLabel
      disabled:
        - name: "*" # disable all default plugins
  pluginConfig:
    - name: ScoreByLabel
      args:
        labelKey: "score-by-label"